### ISSUE TITLE
Zu wild:

### ISSUE THREAD

**Issue by Coinners** [Poldi-de/tollerserver.github.io#1]
Du weißt schon, dass Github Pages nur mit **_username_**.github.io funktioniert

**Comment by Poldi-de** [comment]
Ja, es geht aber um die Domain (ranks.tollerserver.ml)

**Comment by Coinners** [comment]
ja, aber du musst es trotzdem **_username_**.github.io nennen und dann über die Domain verbinden

**Comment by Poldi-de** [comment]
Probiere aus, es klappt ;)

**Comment by Coinners** [comment]
aber es steht so in den Docs 😌

**Comment by Poldi-de** [comment]
Wenn es trotzdem klappt, hä?

**Comment by Coinners** [comment]
naja, aber SSL scheint ja nicht zu funktionieren 👀
